### ISSUE TITLE
invalid address 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [binance-chain/java-sdk#15]
Hello everyone

this issue is related to javascript_SDK and java_SDK if https://testnet.binance.org use javascript_sdk .

i use this private key to get address : 90335b9d2153ad1a9799a3ccc070bd64b4164e9642ee1dd48053c33f9a3a05e9

but returned address in java_sdk and https://testnet.binance.org is differ
address from JAVA_SDK : bnc1hgm0p7khfk85zpz5v0j8wnej3a90w7098fpxyh
address from testnet.binanace.org : tbnb1hgm0p7khfk85zpz5v0j8wnej3a90w709zzlffd

i know bnc or tbnb is hrp and there is 1hgm0p7khfk85zpz5v0j8wnej3a90w709 in both

**Comment by qinshaohui** [comment]
This works for me:
```
Wallet wallet = new Wallet("90335b9d2153ad1a9799a3ccc070bd64b4164e9642ee1dd48053c33f9a3a05e9", BinanceDexEnvironment.TEST_NET);
System.out.println("address: " + wallet.getAddress());
```
address: tbnb1hgm0p7khfk85zpz5v0j8wnej3a90w709zzlffd
