### ISSUE TITLE
mvn compilation failure

### ISSUE THREAD

**Issue by jingleizhang** [binance-chain/java-sdk#20]
master分支：

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /binance/java-sdk/target/generated-sources/protobuf/grpc-java/types/ABCIApplicationGrpc.java:[20,18] 找不到符号
  符号:   类 Generated
  位置: 程序包 javax.annotation
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by huangsuyu** [comment]
> master分支：
> 
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /binance/java-sdk/target/generated-sources/protobuf/grpc-java/types/ABCIApplicationGrpc.java:[20,18] 找不到符号
> 符号: 类 Generated
> 位置: 程序包 javax.annotation
> [INFO] 1 error
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE

please check your network.

It works fine on my end.
