### ISSUE TITLE
get block transactions doesn't work

### ISSUE THREAD

**Issue by vladmelnyk** [binance-chain/java-sdk#21]
I am using sdk method 
`binanceDexApiNodeClient.getBlockTransactions(10226506L)`
I was expecting to return not empty list (look here https://testnet-explorer.binance.org/block/10226506). However, I am getting empty list using rpc method. Could you help me on this ?

**Comment by jiangkai-rq** [comment]
We only support the transfer transaction currently. We will support more transaction types recently. Thanks for your reminding.
