### ISSUE TITLE
walletconnect problem

### ISSUE THREAD

**Issue by liweiww123** [binance-chain/java-sdk#33]
why user the walletconnect library in andorid wallet.

Scan login and  balance transfer were ok.

but the buy and sell transaction  has a problem,  your website always send the same message to the phone.unable to stop.

I can't judge what caused the problem.

And after balance transfer success , try buy and sell transaction again ,was normal .

thanks.

**Comment by huangsuyu** [comment]
> why user the walletconnect library in andorid wallet.
> 
> Scan login and balance transfer were ok.
> 
> but the buy and sell transaction has a problem, your website always send the same message to the phone.unable to stop.
> 
> I can't judge what caused the problem.
> 
> And after balance transfer success , try buy and sell transaction again ,was normal .
> 
> thanks.

Duplicate issue here: https://github.com/WalletConnect/kotlin-walletconnect-lib/issues/9
