### ISSUE TITLE
Transaction history page will display duplicate data

### ISSUE THREAD

**Issue by liweiww123** [binance-chain/java-sdk#38]
just like :
https://testnet-dex.binance.org/api/v1/transactions?side=RECEIVE&address=tbnb16hywxpvvkaz6cecjz89mf2w0da3vfeg6z6yky2&offset=3&limit=30&endTime=1558667761000

https://testnet-dex.binance.org/api/v1/transactions?side=RECEIVE&address=tbnb16hywxpvvkaz6cecjz89mf2w0da3vfeg6z6yky2&offset=4&limit=30&endTime=1558667761000

**Comment by huangsuyu** [comment]
Hello,

The retuned value is expected. You will see some results in common if the offset difference is small.
