### ISSUE TITLE
Can`t get transaction by block height

### ISSUE THREAD

**Issue by prettyCoders** [binance-chain/java-sdk#39]
It return empty every block. Connecting to my own full node,Use main_net.

![image](https://user-images.githubusercontent.com/36216120/58623409-879d9180-8300-11e9-9e32-234396e16b39.png)

**Comment by guagualvcha** [comment]
there is a config file , usually `config/config.toml`,  
![image](https://user-images.githubusercontent.com/7310198/59193354-fe1b7880-8bb7-11e9-9dd5-b55c8e91f1be.png)
please make sure above config(indexer = "kv", index_tags = "tx.height") is open, then restart the full node
