### ISSUE TITLE
com.binance.dex.api.proto not available

### ISSUE THREAD

**Issue by tigerich** [binance-chain/java-sdk#54]
When I tried to utilize the client API, I found ```com.binance.dex.api.proto``` is not available. Hence the project can't be compiled properly.

POM file does not seem to include it either.

Am I missing anything here?

**Comment by syuukawa** [comment]
Yes, The same question,

**Comment by fletcher142** [comment]
The Class under `com.binance.dex.api.proto` need to be generated by protobuf. It was not written by SDK developer.The POM file has included the related plugin to help you generated these code.
![image](https://user-images.githubusercontent.com/42368365/61344253-2c5d3980-a883-11e9-89b4-244e70246a8a.png)
So you can easily generate these classes with the command:
`mvn compile`
Or if you use IDE like IntelliJ IDEA,you can click here like blew:
![image](https://user-images.githubusercontent.com/42368365/61344478-f8cedf00-a883-11e9-9e57-4fac19d43d5b.png)

**Comment by syuukawa** [comment]
Thanks ；Got it ；


On Jul 17, 2019, at 11:14 AM, fletcher142 <notifications@github.com<mailto:notifications@github.com>> wrote:


The Class under com.binance.dex.api.proto need to be generated by protobuf. It was not written by SDK developer.The POM file has included the related plugin to help you generated these code.
[image]<https://user-images.githubusercontent.com/42368365/61344253-2c5d3980-a883-11e9-89b4-244e70246a8a.png>
So you can easily generate these classes with the command:
mvn compile
Or if you use IDE like IntelliJ IDEA,you can click here like blew:
[image]<https://user-images.githubusercontent.com/42368365/61344478-f8cedf00-a883-11e9-9e57-4fac19d43d5b.png>
