### ISSUE TITLE
java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by abyssal0** [binance-chain/java-sdk#58]
java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
	at com.binance.dex.api.client.impl.BinanceDexApiNodeClientImpl.getNodeInfo(BinanceDexApiNodeClientImpl.java:49) ~[binance-dex-api-client-1.0.0.jar!/:na]
	 ....
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232) ~[okio-1.15.0.jar!/:na]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[okio-1.15.0.jar!/:na]
	... 17 common frames omitted
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[na:1.8.0_161]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_161]
	at okio.Okio$2.read(Okio.java:140) ~[okio-1.15.0.jar!/:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.15.0.jar!/:na]
	... 38 common frames omitted

When I perform the API times wrong, binanceDexNodeApi.Transfer (transfer, NodeWallet, options, true) has been an error, but Blockchain Explorer query execution transfer success. BinanceDexNodeApi.GetNodeInfo() and occasionally as errors

**Comment by fletcher142** [comment]
make sure the way you instantiate `BinanceDexApiNodeClientImpl` is correct
it should be like this 
`BinanceDexApiNodeClient binanceDexNodeApi = BinanceDexApiClientFactory.newInstance().newNodeRpcClient(BinanceDexEnvironment.TEST_NET.getNodeUrl(),BinanceDexEnvironment.TEST_NET.getHrp());` which you can find it in `NodeClientExample`. And put `BinanceDexEnvironment.PROD` instead if u need perform in prod env.

**Comment by abyssal0** [comment]
This is what I do, but occasionally there are timeout issues, is it because local synchronization is slower than network nodes?Can local blocks be slower than the network cause this problem?Or something...

**Comment by fletcher142** [comment]
> network

So you are trying connect to the full node which is running in your local env.? Then you should make sure this node is running normally, and whether the port you filled in is correct.`27147` is the port being exposed as the rpc service of full node by default.

This is tutorial doc. for running a full node.
[](https://docs.binance.org/fullnode.html)

**Comment by fletcher142** [comment]
> This is what I do, but occasionally there are timeout issues, is it because local synchronization is slower than network nodes?Can local blocks be slower than the network cause this problem?Or something...

So you are trying connect to the full node which is running in your local env.? Then you should make sure this node is running normally, and whether the port you filled in is correct.27147 is the port being exposed as the rpc service of full node by default.

This is tutorial doc. for running a full node.
https://docs.binance.org/fullnode.html

**Comment by abyssal0** [comment]
Full node is correct.Data can be normally obtained, and transactions can be normally pushed to the blockchain.It's just that sometimes there's a return timeout and you can't get the results.I suspect the slow synchronization of the nodes.Sometimes nodes are 1000-2000 slower than blockchain explorer in querying blocknumber

**Comment by abyssal0** [comment]
What causes slow synchronization of nodes?In what ways can you speed up node synchronization?

**Comment by guagualvcha** [comment]
> What causes slow synchronization of nodes?In what ways can you speed up node synchronization?

Hi,  Are you building your node? If so, can you past any logs of your running node?
